markdownでの出力
mom0tomo/blog-post-salvager pull request #8
Opened 2017-12-01 01:10 UTC by tunagohan

## 概要

markdownとして複数ファイルの出力を可能にする

## 注意

markdownとしてではなくただのファイル出力。
ファイルタイプがどうなっているのか要確認

2017-12-01 01:49 UTC, mi-bear requested changes

2017-12-01 01:49 UTC, mi-bear commented on markdown.go
> +      defer file.Close()
https://mattn.kaoriya.net/software/lang/go/20151212021608.htm

2017-12-01 02:00 UTC, tunagohan commented on markdown.go
> +      defer file.Close()
(mattnの見て青冷め。やばいコードを書いてしまった疑惑)

2017-12-01 03:43 UTC, mom0tomo commented on markdown.go
> +      defer file.Close()
a!これやったことあるwww

2017-12-01 05:16 UTC, tunagohan commented
forの中で結局 `defer file.Close()`しているようにも見えなくもないので
あとはももさん任せます！！
一応取得はできてるっぽいですが、全ファイル取得にはなっていないので要注意

2018-01-14 13:06 UTC, mom0tomo commented
env-exampleがめっちゃ整備されてて感動...
マジります！

2018-01-14 13:07 UTC, merged

2018-01-14 13:09 UTC, mom0tomo commented on http.go
> +	url := "https://api.docbase.io/teams/" + team_domain + "/posts?page=" + pages + "&per_page=20&q=author_id:" + author_id
めっちゃみやすい！

2018-01-14 13:09 UTC, mom0tomo commented on env-example
> +# Please get access token from your team's settings.
最高のexampleですね

2018-01-14 13:09 UTC, mom0tomo commented on markdown.go
> +func markdown(articles Article) (error) {
markdownってのにしてくれたのね！ありがとう

2018-01-14 13:09 UTC, mom0tomo commented on markdown.go
> +				file, err := createFile(title)
あれ、インデント野郎がいる予感...